### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by frenzylag777** [KamikotoTkach/MTFconverter#2]
![image](https://github.com/KamikotoTkach/MTFconverter/assets/107318308/bd3f4c87-4e40-4c4d-b1a9-e6ed79b2378c)

**Comment by KamikotoTkach** [comment]
Какая система, какая джава? При каких условиях возникает ошибка?

**Comment by frenzylag777** [comment]
на скрине вин 10, сейчас 11, джава 8, условия: простой запуск нажатием мыши

**Comment by KamikotoTkach** [comment]
Установите Java 17 или выше

**Comment by frenzylag777** [comment]
вроде как джава 17 тоже пробовал, не помогло

**Comment by KamikotoTkach** [comment]
Запустите приложение через командную строку:
* Откройте консоль в директории с исполняемым файлом приложения
* Пропишите `java -jar MTFconverter-ru.jar`

И скиньте скриншот консоли после выполнения

**Comment by frenzylag777** [comment]
Я запустил команду `"C:\Program Files\Java\jdk-17.0.10\bin\java.exe" -jar MTFconverter-ru.jar` и всё сработало, спасибо!

**Comment by KamikotoTkach** [comment]
Я полагаю, у вас в path прописана 8 ява.
